# settings.toml

# ===================================================================
# IoT Environmental Monitoring - Konfigurationsdatei
# Diese Datei wird vom Raspberry Pi Pico W beim Start gelesen.
# Bitte die WLAN-Daten vor Ort anpassen.
# ===================================================================

# --- Geräteeinstellungen ---
# Eindeutiger Name für diesen Sensor, wird in den MQTT-Nachrichten verwendet.
device_id = "Sensor-Schmidt-Naegele"
names = "Schmidt-Naegele"

# Optionaler, menschenlesbarer Standort für das Web-Interface.
location = "Produktionshalle 1, Innsbruck"


# --- WLAN-Einstellungen ---
# SSID (Name) und Passwort des lokalen WLAN-Netzwerks.
# WICHTIG: Diese müssen vor Ort eingetragen werden!
CIRCUITPY_WIFI_SSID = "WIFINAME"
CIRCUITPY_WIFI_PASSWORD = "WIFIPassword"


# --- MQTT Broker Einstellungen ---
MQTT_BROKER = "158.180.44.197"
MQTT_PORT = 1883
MQTT_USER = "bobm"
MQTT_PASSWORD = "letmein"
MQTT_CLIENT_ID = "pico_w_client"
MQTT_BASE_TOPIC = "iiot/group/test/sensor"
READING_INTERVAL = 30

# Topics sind wie "Kanäle", auf denen Nachrichten gesendet werden.
# Das Haupt-Topic für die Sensordaten (Temperatur, Luftfeuchtigkeit).
telemetry_topic_temperature = "iiot/group/Schmidt-Naegele/sensor/temperature"
telemetry_topic_humidity = "iiot/group/Schmidt-Naegele/sensor/humidity"
# Das Topic für Statusmeldungen (z.B. "online", "rebooting").
status_topic = "iiot/group/Schmidt-Naegele/sensor/status"


# --- Sensor & Applikations-Einstellungen ---
# Das Intervall in Sekunden, in dem Daten gelesen und gesendet werden.
reading_interval_seconds = 10

# Der GPIO Pin des Raspberry Pi Pico, an dem das Datenkabel des
# DHT22-Sensors angeschlossen ist
sensor_pin = 22